# SPDX-FileCopyrightText: Copyright (c) 2024-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

load("//:rules.bzl", "runai_cc_library")

runai_cc_library(
    name = "testing",
    srcs = ["main.cc"],
    deps = ["@com_google_googletest//:gtest"],
)
