# SPDX-FileCopyrightText: Copyright (c) 2024-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

load("//:rules.bzl", "runai_cc_auto_library")

runai_cc_auto_library(
    name = "file",
    deps = [
        "//common/exception",
        "//streamer/impl/reader",
        "//streamer/impl/config/config",
        "//utils/fd",
    ],
)
