# SPDX-FileCopyrightText: Copyright (c) 2024 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

load("//:rules.bzl", "runai_cc_library")

runai_cc_library(
    name = "portability",
    srcs = ["portability.c"],
    linkstatic = True,
    alwayslink = True,
)
