name: Build and Push DevContainer

on:
  push:
    branches:
      - master
    paths:
      - '.devcontainer/**'
      - '.github/workflows/devcontainer.yml'
      - '.github/workflows/build-devcontainer.yml'
  workflow_dispatch:

jobs:
  build-devcontainer:
    name: Build & Push DevContainer Image
    if: github.ref == 'refs/heads/master'
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        arch: [x86_64, aarch64]
    uses: ./.github/workflows/devcontainer.yml
    with:
      publish: true
      arch: ${{ matrix.arch }}
